"""Add verification models and enhanced functionality

Revision ID: 0ea361e979f4
Revises: 600a4ae2b27c
Create Date: 2025-10-05 22:55:34.564084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ea361e979f4'
down_revision = '600a4ae2b27c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aishe_registry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('aishe_code', sa.String(length=50), nullable=False),
    sa.Column('institution_name', sa.String(length=200), nullable=False),
    sa.Column('institution_type', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('established_year', sa.Integer(), nullable=True),
    sa.Column('accreditation_status', sa.String(length=50), nullable=True),
    sa.Column('university_affiliation', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('verification_level', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aishe_code')
    )
    op.create_table('apar_registry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('apar_id', sa.String(length=50), nullable=False),
    sa.Column('teacher_name', sa.String(length=200), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('institution_name', sa.String(length=200), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('verification_level', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apar_id')
    )
    op.create_table('user_verification_status',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('aadhaar_verified', sa.Boolean(), nullable=True),
    sa.Column('profile_verified', sa.Boolean(), nullable=True),
    sa.Column('document_verified', sa.Boolean(), nullable=True),
    sa.Column('manual_verification_required', sa.Boolean(), nullable=True),
    sa.Column('overall_status', sa.String(length=20), nullable=True),
    sa.Column('verification_score', sa.Float(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('verified_by', sa.String(length=36), nullable=True),
    sa.Column('verification_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('verification_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('verification_type', sa.String(length=50), nullable=False),
    sa.Column('verification_data', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result_message', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('verified_by', sa.String(length=36), nullable=True),
    sa.Column('verification_method', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('additional_checks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification_logs')
    op.drop_table('user_verification_status')
    op.drop_table('apar_registry')
    op.drop_table('aishe_registry')
    # ### end Alembic commands ###
