"""Initial migration with enhanced models

Revision ID: 600a4ae2b27c
Revises: 
Create Date: 2025-10-05 22:40:15.535822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '600a4ae2b27c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('government_schemes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scheme_name', sa.String(length=200), nullable=False),
    sa.Column('scheme_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('eligibility_criteria', sa.Text(), nullable=True),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.Column('application_process', sa.Text(), nullable=True),
    sa.Column('scheme_category', sa.String(length=100), nullable=True),
    sa.Column('target_group', sa.String(length=100), nullable=True),
    sa.Column('funding_amount', sa.Float(), nullable=True),
    sa.Column('max_beneficiaries', sa.Integer(), nullable=True),
    sa.Column('current_beneficiaries', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('ministry_department', sa.String(length=200), nullable=True),
    sa.Column('contact_details', sa.Text(), nullable=True),
    sa.Column('documents_required', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_code')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('aadhaar_id', sa.String(length=12), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aadhaar_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('institutions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('aishe_code', sa.String(length=50), nullable=False),
    sa.Column('nirf_rank', sa.Integer(), nullable=True),
    sa.Column('schemes', sa.Text(), nullable=True),
    sa.Column('institution_name', sa.String(length=200), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('established_year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aishe_code')
    )
    op.create_table('scheme_applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scheme_id', sa.String(length=36), nullable=False),
    sa.Column('applicant_id', sa.String(length=36), nullable=False),
    sa.Column('applicant_type', sa.String(length=20), nullable=False),
    sa.Column('application_status', sa.String(length=50), nullable=True),
    sa.Column('submitted_documents', sa.Text(), nullable=True),
    sa.Column('application_data', sa.Text(), nullable=True),
    sa.Column('review_comments', sa.Text(), nullable=True),
    sa.Column('approved_amount', sa.Float(), nullable=True),
    sa.Column('application_date', sa.DateTime(), nullable=True),
    sa.Column('review_date', sa.DateTime(), nullable=True),
    sa.Column('disbursement_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scheme_id'], ['government_schemes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('apar_id', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('evaluations', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apar_id')
    )
    op.create_table('students',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('enrollment_no', sa.String(length=50), nullable=False),
    sa.Column('courses', sa.Text(), nullable=True),
    sa.Column('projects', sa.Text(), nullable=True),
    sa.Column('certificates', sa.Text(), nullable=True),
    sa.Column('achievements', sa.Text(), nullable=True),
    sa.Column('academic_progress', sa.Float(), nullable=True),
    sa.Column('current_gpa', sa.Float(), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('institution_id', sa.String(length=36), nullable=True),
    sa.Column('government_schemes', sa.Text(), nullable=True),
    sa.Column('career_goals', sa.Text(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    op.drop_table('teachers')
    op.drop_table('scheme_applications')
    op.drop_table('institutions')
    op.drop_table('users')
    op.drop_table('government_schemes')
    # ### end Alembic commands ###
